matrix:
  include:
  - language: python
    install:
    - pip install codespell
    script:
    - codespell --skip=".git,*.png"

  - language: go
    go:
    - "1.11.x"
    - next
    before_install:
    - go get github.com/mattn/goveralls
    script:
    - make style test build
    - $GOPATH/bin/goveralls -service=travis-ci
