apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        name: {{ template "fullname" . }}
      name: {{ template "fullname" . }}
    spec:
      containers:
        - name: trickster
          image: {{ template "trickster.image" . }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cfg-volume
              mountPath: /etc/trickster
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: cfg-volume
          configMap:
            name: {{ template "fullname" . }}-conf
            items:
              - key: trickster-conf
                path: trickster.conf
      serviceAccount: {{ .Release.Name }}-trickster
      serviceAccountName: {{ .Release.Name }}-trickster

