apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
  name: {{ .Release.Name }}-trickster
  labels:
    release: "{{ .Release.Name }}"
spec:
  ports:
    - port: {{ .Values.listenPort }}
      targetPort: {{ .Values.listenPort }}
      name: metrics
  selector:
    name: {{ .Release.Name }}-trickster
